/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dostihy.Hra;
import dostihy.Hrac;
import dostihy.Policko;
import java.awt.Graphics;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author wentsa
 */
public class HerniPlocha extends javax.swing.JFrame {

    Hra hra;
    /**
     * Creates new form HerniPlocha
     * @param hra
     */
    public HerniPlocha(Hra hra) {
        this.hra=hra;
        
        initComponents();
        
        nactiHrace();
        nactiPole();
        nactiKostku();
        
        plocha.add(hra.getStatusBox());
        hra.getStatusBox().setLocation(50, 650);
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nacitacSouboru = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        plocha = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(new ImageIcon("res/plocha.jpg").getImage(), 0, 0, null);
            }
        };
        stred = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(new ImageIcon("res/stred.jpg").getImage(), 0, 0, null);
            }
        };
        prava = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(new ImageIcon("res/prava.jpg").getImage(), 0, 0, null);
            }
        };
        menuBar = new javax.swing.JMenuBar();
        soubor = new javax.swing.JMenu();
        nacist = new javax.swing.JMenuItem();
        upravit = new javax.swing.JMenu();

        nacitacSouboru.setAcceptAllFileFilterUsed(false);
        nacitacSouboru.setCurrentDirectory(new java.io.File("/home/wentsa"));
        nacitacSouboru.setDialogTitle("");
        nacitacSouboru.setFileFilter(new FileNameExtensionFilter("Ulozene hry (.dss)", "DSS"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 255, 17));
        jPanel1.setBorder(null);
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plocha.setBackground(new java.awt.Color(0, 255, 221));
        plocha.setBorder(null);
        plocha.setMaximumSize(new java.awt.Dimension(700, 700));
        plocha.setMinimumSize(new java.awt.Dimension(700, 700));
        plocha.setLayout(new javax.swing.OverlayLayout(plocha));
        jPanel1.add(plocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 701));

        stred.setBackground(new java.awt.Color(0, 176, 255));
        stred.setBorder(null);
        stred.setMaximumSize(new java.awt.Dimension(100, 700));
        stred.setMinimumSize(new java.awt.Dimension(100, 700));
        stred.setPreferredSize(new java.awt.Dimension(100, 700));
        stred.setLayout(new javax.swing.OverlayLayout(stred));
        jPanel1.add(stred, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        prava.setBackground(new java.awt.Color(0, 108, 255));
        prava.setBorder(null);
        prava.setMaximumSize(new java.awt.Dimension(480, 700));
        prava.setMinimumSize(new java.awt.Dimension(480, 700));
        prava.setName(""); // NOI18N
        prava.setLayout(new javax.swing.OverlayLayout(prava));
        jPanel1.add(prava, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 480, 700));

        menuBar.setBackground(new java.awt.Color(19, 19, 19));
        menuBar.setBorder(null);
        menuBar.setForeground(new java.awt.Color(232, 232, 232));

        soubor.setText("Soubor");

        nacist.setText("Nacist hru");
        nacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacistActionPerformed(evt);
            }
        });
        soubor.add(nacist);

        menuBar.add(soubor);

        upravit.setText("Upravy");
        menuBar.add(upravit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacistActionPerformed
        nacitacSouboru.showOpenDialog(soubor);
    }//GEN-LAST:event_nacistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HerniPlocha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HerniPlocha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HerniPlocha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HerniPlocha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HerniPlocha().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nacist;
    private javax.swing.JFileChooser nacitacSouboru;
    private javax.swing.JPanel plocha;
    private javax.swing.JPanel prava;
    private javax.swing.JMenu soubor;
    private javax.swing.JPanel stred;
    private javax.swing.JMenu upravit;
    // End of variables declaration//GEN-END:variables

    private void nactiHrace() {
        //plocha.setLayout(new OverlayLayout(plocha));
        //prava.setLayout(new OverlayLayout(prava));
        for (Hrac h : hra.getHraci()) {
            plocha.add(h.getFigurka());
            prava.add(h.getJmenovka());
            prava.add(h.getJmenovka().getPuntik());
            System.out.println(h.getJmeno() + " " + h.getFigurka().getPozice());
        }
        //prava.add(new JLabel("ahoj"));
        
        //pack();
        
    }
    
    private void nactiPole() {
        //plocha.setLayout(new OverlayLayout(plocha));
        for (final Policko p : hra.getPolicka()) {
            if(p.isVlastnicka()) {
                
                p.setOpaque(false);
                p.setContentAreaFilled(false);
                p.setBorderPainted(false);
                p.addActionListener(new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        try {
                            p.getKarta().zobraz();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(HerniPlocha.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                plocha.add(p.getObsazFigurka());
                plocha.add(p);
            }
        }
        //pack();
    }
    
    private void nactiKostku() {
        prava.add(hra.getKostka());
    }
    
    
    
}
