/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dostihy.Control;
import dostihy.Hra;
import dostihy.Hrac;
import dostihy.Policko;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import karty.VlastnickaKarta;

/**
 *
 * @author wentsa
 */
public class ProdejGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProdejGUI
     */
    private final Hra hra;
    private final Hrac hrac;
    private final Set<VlastnickaKarta> karty;
    private final String[] sKarty;
    private boolean prodal = false;

    public ProdejGUI(Hrac hrac) {
        this.hra = Control.hra;
        this.hrac = hrac;
        karty = this.hrac.getKarty();
        sKarty = new String[karty.size()];
        int i = 0;
        for (VlastnickaKarta k : karty) {
            sKarty[i++] = k.toString();
        }
        initComponents();
        vypis.setContentType("text/html");
        celkem.setText("");
        ListSelectionListener listSelectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                boolean adjust = listSelectionEvent.getValueIsAdjusting();
                if (!adjust) {
                    JList list = (JList) listSelectionEvent.getSource();
                    Object selectionValues[] = list.getSelectedValues();
                    int sirka = ProdejGUI.this.vypis.getWidth();
                    String text = new String("<html><table width=" + sirka + ">");
                    int suma = 0;
                    for (Object o : selectionValues) {
                        VlastnickaKarta k = null;
                        for (VlastnickaKarta c : ProdejGUI.this.karty) {
                            if (c.toString().equals(o.toString())) {
                                k = c;
                                break;
                            }
                        }
                        suma += k.getPorizovaciCena();
                        text = text.concat("<tr><td>" + k.toString() + "</td><td align=right>" + k.getPorizovaciCena() + ",-</td></tr>");
                    }
                    text = text.concat("</table></html>");

                    ProdejGUI.this.vypis.setText(text);
                    ProdejGUI.this.celkem.setText("<html><table width=" + sirka + "><tr><td>CELKEM</td><td align=right>" + suma + ",-</td></tr></table></html>");
                }
            }
        };
        
        jList1.addListSelectionListener(listSelectionListener);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                ProdejGUI.this.prodal = true;
            }

        });
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        vypis = new javax.swing.JTextPane();
        celkem = new javax.swing.JLabel();
        button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(1);

        jScrollPane1.setBorder(null);

        jList1.setBorder(null);
        jList1.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return ProdejGUI.this.sKarty.length; }
            public Object getElementAt(int i) { return ProdejGUI.this.sKarty[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jSplitPane2.setBorder(null);
        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setDividerSize(0);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setBorder(null);
        jSplitPane3.setDividerLocation(280);
        jSplitPane3.setDividerSize(0);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        vypis.setEditable(false);
        vypis.setBorder(null);
        jScrollPane2.setViewportView(vypis);

        jSplitPane3.setLeftComponent(jScrollPane2);

        celkem.setText("jLabel1");
        jSplitPane3.setRightComponent(celkem);

        jSplitPane2.setTopComponent(jSplitPane3);

        button.setText("jButton1");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        jSplitPane2.setRightComponent(button);

        jSplitPane1.setRightComponent(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        Object selectionValues[] = jList1.getSelectedValues();
        Set<VlastnickaKarta> vymazat = new HashSet<>();
        for (Object o : selectionValues) {
            VlastnickaKarta k = null;
            for (VlastnickaKarta c : ProdejGUI.this.karty) {
                if (c.toString().equals(o.toString())) {
                    k = c;
                    break;
                }
            }
            vymazat.add(k);
        }
        for (VlastnickaKarta k : vymazat) {
            hrac.pricti(k.getPorizovaciCena());
            Policko p = hra.getPolicka().get(k.getPozice());
            p.setObsazeno(false);
            p.setMajitel(null);
            p.getObsazFigurka().setObsazeno(false);
            karty.remove(k);
        }
        prodal = true;
        dispose();
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel celkem;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextPane vypis;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the prodal
     */
    public boolean isProdal() {
        return prodal;
    }
}
