/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import MVC.HerniPlochaView;
import MVC.HerniPlochaController;
import dostihy.Control.DataHraci;
import dostihy.Hra;
import java.awt.CardLayout;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import pomocne.ListenerTask;
import pomocne.MyCardLayout;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author wentsa
 */
public class TEST extends javax.swing.JFrame {

    /**
     * Creates new form TEST
     */
    Menu1 menu = new Menu1();
    VolbaHracu1 volba = new VolbaHracu1();
    HerniPlochaView plocha = HerniPlochaController.getInstance().getView();
    Vysledky vysledky = new Vysledky();
    private boolean konec=false;

    public TEST() {
        System.out.println("test na " + Thread.currentThread().toString());
        initComponents();
        jPanel2.add(menu, "menu");
        jPanel2.add(volba, "volba");
        jPanel2.add(plocha, "plocha");
        jPanel2.add(vysledky, "vysledky");
        pack();
        setLocationRelativeTo(null);
    }

    public void zalozHrace(DataHraci d) throws InterruptedException {
        Hra.getInstance().zalozHrace(d);
        HerniPlochaController.getInstance().nactiHrace();
        nastavPlochu();
        tahni();
    }

    public void nactiHru() {
        NacitacSouboru nacitac = new NacitacSouboru();
        int zvoleno = nacitac.showOpenDialog(null);
        if (zvoleno == JFileChooser.APPROVE_OPTION) {
            nacitac.vyhodnot();
        } else {
            nastavMenu();
        }
    }

    public void nastavMenu() {
        MyCardLayout cardLayout = (MyCardLayout) jPanel2.getLayout();
        cardLayout.show(jPanel2, "menu");
        pack();
        setLocationRelativeTo(null);
    }

    public void nastavVolbu() {
        MyCardLayout cardLayout = (MyCardLayout) jPanel2.getLayout();
        cardLayout.show(jPanel2, "volba");
        pack();
        setLocationRelativeTo(null);
    }

    public void nastavPlochu() throws InterruptedException {
        MyCardLayout cardLayout = (MyCardLayout) jPanel2.getLayout();
        cardLayout.removeLayoutComponent(plocha);
        jPanel2.remove(plocha);
        plocha = null;
        plocha = HerniPlochaController.getInstance().getView();
        jPanel2.add(plocha, "plocha");
        jPanel2.revalidate();
        jPanel2.repaint();
        cardLayout.show(jPanel2, "plocha");
        pack();
        setLocationRelativeTo(null);
    }

    public void nastavVysledky() {
        System.out.println("qweweq   " + Thread.currentThread());
        vysledky.vyplnTabulku(Hra.getInstance().getVyherci());
        MyCardLayout cardLayout = (MyCardLayout) jPanel2.getLayout();
        cardLayout.show(jPanel2, "vysledky");
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(0);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("menu");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("vyber");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("plocha");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("vysledky");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1145, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new MyCardLayout());

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        nastavMenu();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        nastavVolbu();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        try {
            nastavPlochu();
        } catch (InterruptedException ex) {
            Logger.getLogger(TEST.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        nastavVysledky();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TEST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    public void tahni() throws InterruptedException {
        (new ListenerTask<Void, String>(Hra.getInstance().getTah()) {

            @Override
            protected void process(List<String> chunks) {
                System.out.println("dostal jsem chunk");
                String chunk=chunks.get(chunks.size()-1);
                switch (chunk) {
                    case "zapni":
                        HerniPlochaController.getInstance().zapniTlacitko();
                        break;
                    case "vypni":
                        HerniPlochaController.getInstance().vypniTlacitko();
                        break;
                    default: {
                        chunk=chunk.substring(3);
                        Hra.getInstance().getStatusBox().setText(chunk);
                        Hra.getInstance().getStatusBox().repaint();
                        System.out.println("     " + chunk.toUpperCase());
                    } break;
                }
            }
            @Override
            protected void done() {
                TEST.this.nastavVysledky();
            }
            
        }).execute();
    }

    public void setKonec(boolean konec) {
        this.konec=konec;
    }

}
